_wandb:
    value:
        cli_version: 0.24.1
        e:
            cy1pdrljagvnbmdwpxzad7ev3bzmf2t0:
                args:
                    - --num_episodes=3000
                    - --checkpoint=3000
                    - --use_wandb
                codePath: final-project\gobang\submission.py
                codePathLocal: submission.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "267360661504"
                        used: "239943372800"
                email: hugengyuan123@gmail.com
                executable: D:\anaconda3\envs\ai25\python.exe
                git:
                    commit: c85caaabf30a55861d079637a5ca1f3ea2d4e4d6
                    remote: git@github.com:Coke-debugger/final-Project1.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-5206bc48-36f0-553b-1b83-4d4407913938
                host: LAPTOP-B690SUI1
                memory:
                    total: "16344801280"
                os: Windows-10-10.0.22631-SP0
                program: D:\AI3002\final-Project1\final-project\gobang\submission.py
                python: CPython 3.10.18
                root: D:\AI3002\final-Project1\final-project\gobang
                startedAt: "2026-01-31T08:31:40.820888Z"
                writerId: cy1pdrljagvnbmdwpxzad7ev3bzmf2t0
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.24.1
            "8":
                - 3
            "12": 0.24.1
            "13": windows-amd64
board_size:
    value: 12
bound:
    value: 5
checkpoint:
    value: 3000
num_episodes:
    value: 3000
